name: make LaTeX

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            apk add make
            bash .ci/travis/make_all.sh
      - name: Zip all PDFs
        run: |
          bash .ci/travis/zip_pdfs.sh
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          title: "Latest PDFs"
          prerelease: false
          files: |
            ./notes/**/tutorial_*.slides.pdf
            ./notes/**/tutorial_*.notes.pdf
            tutorial_*.zip
